services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"

volumes:
  mongo-data:
